config/routes.rb
Rails.application.routes.draw do
  namespace :admins do
    resources :categories
    resources :types
  end   
  root "indexes#index"
  resources :indexes
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  CATEGORY_PARAMS = [:id, :name, :description]

  has_many :category_types, dependent: :destroy
  has_many :types, through: :category_types
end

app/models/category_type.rb
class CategoryType < ApplicationRecord
  belongs_to :category
  belongs_to :type
end

app/models/company.rb
class Company < ApplicationRecord
  has_many :company_types, dependent: :destroy
  has_many :types, through: :company_types
end

app/models/company_type.rb
class CompanyType < ApplicationRecord
  belongs_to :company
  belongs_to :type
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :company
  belongs_to :category
  has_many :product_tags, dependent: :destroy
  has_many :tags, through: product_tags
end

app/models/product_tag.rb
class ProductTag < ApplicationRecord
end

app/models/tag.rb
class Tag < ApplicationRecord
  has_many :product_tags, dependent: :destroy
  has_many :products, through: :product_tags
end

app/models/type.rb
class Type < ApplicationRecord
  has_many :company_types, dependent: :destroy
  has_many :category_types, dependent: :destroy
  has_many :companies, through: :company_types
  has_many :categories, through: :category_types
end

app/controllers/admins/categories_controller.rb
class Admins::CategoriesController < ApplicationController
  before_action :load_categories, only: :index  
  before_action :load_category, only: [:update, :destroy, :edit]  

  layout "admin"

  def index
    
  end

  def new
    @category = Category.new
  end

  def edit
    
  end

  def update
    @category.update_attributes category_params
    if @category.save
      flash[:success] = t("messages.update_success")
      redirect_to admins_categories_path
    else
      flash[:danger] = t("messages.update_failed")
      redirect_to root_path
    end
  end

  def destroy
    return unless @category.present?
    @category.try :destroy
    redirect_to admins_categories_path
  end

  def create
    @category = Category.new category_params
    if @category.save
      redirect_to admins_categories_path
    else
      redirect_to root_path
    end
  end

  private
  def load_categories
    @categories = Category.all
  end

  def category_params
    params.require(:category).permit Category::CATEGORY_PARAMS
  end

  def load_category
    @category = Category.find_by id: [params[:id]]
  end
end

app/controllers/admins/types_controller.rb
class Admins::TypesController < ApplicationController
  before_action :load_types, only: :index  
  before_action :load_type, only: [:update, :destroy, :edit]  

  layout "admin"

  def index
    
  end

  def new
    @type = Type.new
  end

  def edit
    
  end

  def update
    @type.update_attributes type_params
    if @type.save
      flash[:success] = t("messages.update_success")
      redirect_to admins_categories_path
    else
      flash[:danger] = t("messages.update_failed")
      redirect_to root_path
    end
  end

  def destroy
    return unless @type.present?
    @type.try :destroy
    redirect_to admins_categories_path
  end

  def create
    @type = Type.new type_params
    if @type.save
      redirect_to admins_categories_path
    else
      redirect_to root_path
    end
  end

  private
  def load_types
    @types = Type.all
  end

  def type_params
    params.require(:type).permit Type::TYPE_PARAMS
  end

  def load_type
    @type = Type.find_by id: [params[:id]]
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/indexes_controller.rb
class IndexesController < ApplicationController
  def index
  	@categories = Category.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admins/categories/edit.html.erb
<%= form_for @category, url: admins_category_path do |f|%>
  <%= f.label :name%>
  <%= f.text_field :name%>
  <%= f.label :description%>
  <%= f.text_area :description%>
  <%= f.submit "Submit" %>
<% end %>

app/views/admins/categories/index.html.erb
<div class="container-fluid jumbotron">
  <table class="table table-striped">
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Delete</th>
      <th>Update</th>
    </tr>
    <% @categories.each do |category| %>
      <tr>
        <td><%= category.name %></td>
        <td><%= category.description %></td>
        <td><%= link_to "Update", edit_admins_category_path(category), class: "btn btn-alert" %></td>
        <td><%= link_to "Delete", admins_category_path(category), method: :delete, class: "btn btn-danger" %></td>
      </tr>
    <% end %>  
  </table>
  <%= link_to "Create", new_admins_category_path, class: "btn btn-success" %>
</div>

app/views/admins/categories/new.html.erb
<%= form_for @category, url: admins_categories_path do |f|%>
  <%= f.label :name%>
  <%= f.text_field :name%>
  <%= f.label :description%>
  <%= f.text_area :description%>
  <%= f.submit "Submit" %>
<% end %>

app/views/admins/shared/_admin_header.html.erb
<nav class="navbar navbar-default navbar-fixed-top">
  <div class="container-fluid">
    <a href="#" class="navbar-brand">Logo</a>
    <ul id="nav-mobile" class="nav navbar-nav">
      <li><%= link_to "Category", admins_categories_path %></li>
      <li><%= link_to "Type", admins_types_path %></li>
      <li><%= link_to "Admin", "#" %></li>
      <li><%= link_to "Product", "#" %></li>
      <li><%= link_to "Company", "#" %></li>
      <li><%= link_to "Tag", "#" %></li>
    </ul>
  </div>
</nav>

app/views/admins/types/edit.html.erb
<%= form_for @type, url: admins_type_path do |f|%>
  <%= f.label :name%>
  <%= f.text_field :name%>
  <%= f.label :description%>
  <%= f.text_area :description%>
  <%= f.submit "Submit" %>
<% end %>

app/views/admins/types/index.html.erb
<table>
  <tr>
    <th>Name</th>
    <th>Description</th>
    <th>Action</th>
  </tr>
  <% @types.each do |type| %>
  <tr>
    <td><%= type.name  %></td>
    <td><<%= type.description  %></td>
    <td><%= link_to "Delete", admins_type_path(type), method: :delete %><%= link_to "Update", edit_admins_type_path(type) %></td>
 </tr>
 <% end %>
 <%= link_to "Create", new_admins_type_path %>
</table>

app/views/admins/types/new.html.erb
<%= form_for @type, url: admins_types_path do |f|%>
  <%= f.label :name%>
  <%= f.text_field :name%>
  <%= f.label :description%>
  <%= f.text_area :description%>
  <%= f.submit "Submit" %>
<% end %>

app/views/admins/types/show.html.erb
<%= form_for @category do |f|%>
  <%= f.label :name%>
  <%= f.text_field :name%>
  <%= f.label :description%>
  <%= f.text_area :description%>
  <%= f.submit "Submit" %>
<% end %>

app/views/indexes/_index_footer.html.erb
<footer id="footer"><!--Footer-->
		<div class="footer-top">
			<div class="container">
				<div class="row">
					<div class="col-sm-2">
						<div class="companyinfo">
							<h2><span>e</span>-shopper</h2>
							<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit,sed do eiusmod tempor</p>
						</div>
					</div>
					<div class="col-sm-7">
						<div class="col-sm-3">
							<div class="video-gallery text-center">
								<a href="#">
									<div class="iframe-img">
										<img src="images/home/iframe1.png" alt="" />
									</div>
									<div class="overlay-icon">
										<i class="fa fa-play-circle-o"></i>
									</div>
								</a>
								<p>Circle of Hands</p>
								<h2>24 DEC 2014</h2>
							</div>
						</div>
						
						<div class="col-sm-3">
							<div class="video-gallery text-center">
								<a href="#">
									<div class="iframe-img">
										<img src="images/home/iframe2.png" alt="" />
									</div>
									<div class="overlay-icon">
										<i class="fa fa-play-circle-o"></i>
									</div>
								</a>
								<p>Circle of Hands</p>
								<h2>24 DEC 2014</h2>
							</div>
						</div>
						
						<div class="col-sm-3">
							<div class="video-gallery text-center">
								<a href="#">
									<div class="iframe-img">
										<img src="images/home/iframe3.png" alt="" />
									</div>
									<div class="overlay-icon">
										<i class="fa fa-play-circle-o"></i>
									</div>
								</a>
								<p>Circle of Hands</p>
								<h2>24 DEC 2014</h2>
							</div>
						</div>
						
						<div class="col-sm-3">
							<div class="video-gallery text-center">
								<a href="#">
									<div class="iframe-img">
										<img src="images/home/iframe4.png" alt="" />
									</div>
									<div class="overlay-icon">
										<i class="fa fa-play-circle-o"></i>
									</div>
								</a>
								<p>Circle of Hands</p>
								<h2>24 DEC 2014</h2>
							</div>
						</div>
					</div>
					<div class="col-sm-3">
						<div class="address">
							<img src="images/home/map.png" alt="" />
							<p>505 S Atlantic Ave Virginia Beach, VA(Virginia)</p>
						</div>
					</div>
				</div>
			</div>
		</div>
		
		<div class="footer-widget">
			<div class="container">
				<div class="row">
					<div class="col-sm-2">
						<div class="single-widget">
							<h2>Service</h2>
							<ul class="nav nav-pills nav-stacked">
								<li><a href="#">Online Help</a></li>
								<li><a href="#">Contact Us</a></li>
								<li><a href="#">Order Status</a></li>
								<li><a href="#">Change Location</a></li>
								<li><a href="#">FAQ’s</a></li>
							</ul>
						</div>
					</div>
					<div class="col-sm-2">
						<div class="single-widget">
							<h2>Quock Shop</h2>
							<ul class="nav nav-pills nav-stacked">
								<li><a href="#">T-Shirt</a></li>
								<li><a href="#">Mens</a></li>
								<li><a href="#">Womens</a></li>
								<li><a href="#">Gift Cards</a></li>
								<li><a href="#">Shoes</a></li>
							</ul>
						</div>
					</div>
					<div class="col-sm-2">
						<div class="single-widget">
							<h2>Policies</h2>
							<ul class="nav nav-pills nav-stacked">
								<li><a href="#">Terms of Use</a></li>
								<li><a href="#">Privecy Policy</a></li>
								<li><a href="#">Refund Policy</a></li>
								<li><a href="#">Billing System</a></li>
								<li><a href="#">Ticket System</a></li>
							</ul>
						</div>
					</div>
					<div class="col-sm-2">
						<div class="single-widget">
							<h2>About Shopper</h2>
							<ul class="nav nav-pills nav-stacked">
								<li><a href="#">Company Information</a></li>
								<li><a href="#">Careers</a></li>
								<li><a href="#">Store Location</a></li>
								<li><a href="#">Affillate Program</a></li>
								<li><a href="#">Copyright</a></li>
							</ul>
						</div>
					</div>
					<div class="col-sm-3 col-sm-offset-1">
						<div class="single-widget">
							<h2>About Shopper</h2>
							<form action="#" class="searchform">
								<input type="text" placeholder="Your email address" />
								<button type="submit" class="btn btn-default"><i class="fa fa-arrow-circle-o-right"></i></button>
								<p>Get the most recent updates from <br />our site and be updated your self...</p>
							</form>
						</div>
					</div>
					
				</div>
			</div>
		</div>
		
		<div class="footer-bottom">
			<div class="container">
				<div class="row">
					<p class="pull-left">Copyright © 2013 E-SHOPPER Inc. All rights reserved.</p>
					<p class="pull-right">Designed by <span><a target="_blank" href="http://www.themeum.com">Themeum</a></span></p>
				</div>
			</div>
		</div>
		
	</footer><!--/Footer-->
	

app/views/indexes/_index_header.html.erb
<header id="header"><!--header-->
		<div class="header_top"><!--header_top-->
			<div class="container">
				<div class="row">
					<div class="col-sm-6">
						<div class="contactinfo">
							<ul class="nav nav-pills">
								<li><a href="tel:+841287474326"><i class="fa fa-phone"></i>01287 474 326</a></li>
								<li><a href="mailto:tuanhv123@gmail.com"><i class="fa fa-envelope"></i>tuanhv123@gmail.com</a></li>
							</ul>
						</div>
					</div>
					<div class="col-sm-6">
						<div class="social-icons pull-right">
							<ul class="nav navbar-nav">
								<li><a href="https://www.facebook.com/tuanhv123"><i class="fa fa-facebook"></i></a></li>
								<li><a href="#"><i class="fa fa-google-plus"></i></a></li>
							</ul>
						</div>
					</div>
				</div>
			</div>
		</div><!--/header_top-->
		
		<div class="header-middle"><!--header-middle-->
			<div class="container">
				<div class="row">
					<div class="col-sm-4">
						<div class="logo pull-left">
							<a href="index.html"><%= image_tag "themes/home/logo.png", alt: "" %></a>
						</div>
						<div class="btn-group pull-right">
							<div class="btn-group">
								<button type="button" class="btn btn-default dropdown-toggle usa" data-toggle="dropdown">
									USA
									<span class="caret"></span>
								</button>
								<!-- TODO Change language -->
								<ul class="dropdown-menu">
									<li><a href="#">Canada</a></li>
									<li><a href="#">UK</a></li>
								</ul>
							</div>
						</div>
					</div>
					<div class="col-sm-8">
						<div class="shop-menu pull-right">
						<!-- TODO nav bar -->
							<ul class="nav navbar-nav">
								<li><a href="#"><i class="fa fa-user"></i> Account</a></li>
								<li><a href="#"><i class="fa fa-star"></i> Wishlist</a></li>
								<li><a href="checkout.html"><i class="fa fa-crosshairs"></i> Checkout</a></li>
								<li><a href="cart.html"><i class="fa fa-shopping-cart"></i> Cart</a></li>
								<li><a href="login.html"><i class="fa fa-lock"></i> Login</a></li>
							</ul>
						</div>
					</div>
				</div>
			</div>
		</div><!--/header-middle-->
	
		<!--header-bottom-->
	<!-- 	<div class="header-bottom">
			<div class="container">
				<div class="row">
					<div class="col-sm-9">
						<div class="navbar-header">
							<button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
								<span class="sr-only">Toggle navigation</span>
								<span class="icon-bar"></span>
								<span class="icon-bar"></span>
								<span class="icon-bar"></span>
							</button>
						</div>
						<div class="mainmenu pull-left">
							<ul class="nav navbar-nav collapse navbar-collapse">
								<li><a href="index.html" class="active">Home</a></li>
								<li class="dropdown"><a href="#">Shop<i class="fa fa-angle-down"></i></a>
                                    <ul role="menu" class="sub-menu">
                                        <li><a href="shop.html">Products</a></li>
										<li><a href="product-details.html">Product Details</a></li> 
										<li><a href="checkout.html">Checkout</a></li> 
										<li><a href="cart.html">Cart</a></li> 
										<li><a href="login.html">Login</a></li> 
                                    </ul>
                                </li> 
								<li class="dropdown"><a href="#">Blog<i class="fa fa-angle-down"></i></a>
                                    <ul role="menu" class="sub-menu">
                                        <li><a href="blog.html">Blog List</a></li>
										<li><a href="blog-single.html">Blog Single</a></li>
                                    </ul>
                                </li> 
								<li><a href="404.html">404</a></li>
								<li><a href="contact-us.html">Contact</a></li>
							</ul>
						</div>
					</div>
					<div class="col-sm-3">
						<div class="search_box pull-right">
							<input type="text" placeholder="Search"/>
						</div>
					</div>
				</div>
			</div>
		</div> -->
		<!--/header-bottom-->
	</header><!--/header-->

app/views/indexes/_index_sidebar.html.erb
<div class="col-sm-3">
					<div class="left-sidebar">
						<h2>Category</h2>
						<div class="panel-group category-products" id="accordian"><!--category-productsr-->
							<% @categories.each do |category| %>
								<div class="panel panel-default">
									<div class="panel-heading">
										<h4 class="panel-title">
											<a data-toggle="collapse" data-parent="#accordian" href="#sportswear">
												<span class="badge pull-right"><i class="fa fa-plus"></i></span>
												<%= category.name%>
											</a>
										</h4>
									</div>
									<div id="sportswear" class="panel-collapse collapse">
										<div class="panel-body">
											<ul>
											<% category.types.each do |type|%>
												<li><%= type.name %></li>
											<% end %>
											</ul>
										</div>
									</div>
								</div>
							<% end %>
						</div><!--/category-products-->
					
						<div class="brands_products"><!--brands_products-->
							<h2>Brands</h2>
							<div class="brands-name">
								<ul class="nav nav-pills nav-stacked">
									<li><a href="#"> <span class="pull-right">(50)</span>Acne</a></li>
									<li><a href="#"> <span class="pull-right">(56)</span>Grüne Erde</a></li>
									<li><a href="#"> <span class="pull-right">(27)</span>Albiro</a></li>
									<li><a href="#"> <span class="pull-right">(32)</span>Ronhill</a></li>
									<li><a href="#"> <span class="pull-right">(5)</span>Oddmolly</a></li>
									<li><a href="#"> <span class="pull-right">(9)</span>Boudestijn</a></li>
									<li><a href="#"> <span class="pull-right">(4)</span>Rösch creative culture</a></li>
								</ul>
							</div>
						</div><!--/brands_products-->
						
						<div class="price-range"><!--price-range-->
							<h2>Price Range</h2>
							<div class="well text-center">
								 <input type="text" class="span2" value="" data-slider-min="0" data-slider-max="600" data-slider-step="5" data-slider-value="[250,450]" id="sl2" ><br />
								 <b class="pull-left">$ 0</b> <b class="pull-right">$ 600</b>
							</div>
						</div><!--/price-range-->
						
						<div class="shipping text-center"><!--shipping-->
							<img src="images/home/shipping.jpg" alt="" />
						</div><!--/shipping-->
					
					</div>
				</div>

app/views/indexes/_index_slider.html.erb
<section id="slider"><!--slider-->
		<div class="container">
			<div class="row">
				<div class="col-sm-12">
					<div id="slider-carousel" class="carousel slide" data-ride="carousel">
						<ol class="carousel-indicators">
							<li data-target="#slider-carousel" data-slide-to="0" class="active"></li>
							<li data-target="#slider-carousel" data-slide-to="1"></li>
							<li data-target="#slider-carousel" data-slide-to="2"></li>
						</ol>
						
						<div class="carousel-inner">
							<div class="item active">
								<div class="col-sm-6">
									<h1><span>E</span>-SHOPPER</h1>
									<h2>Free E-Commerce Template</h2>
									<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. </p>
									<button type="button" class="btn btn-default get">Get it now</button>
								</div>
								<div class="col-sm-6">
									<%= image_tag "themes/home/girl1.jpg", class: "girl img-responsive", alt:"" %>
									<%= image_tag "themes/home/pricing.png", class: "pricing", alt:"" %>
								</div>
							</div>
							<div class="item">
								<div class="col-sm-6">
									<h1><span>E</span>-SHOPPER</h1>
									<h2>100% Responsive Design</h2>
									<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. </p>
									<button type="button" class="btn btn-default get">Get it now</button>
								</div>
								<div class="col-sm-6">
									<%= image_tag "themes/home/girl2.jpg", class: "girl img-responsive", alt:"" %>
									<%= image_tag "themes/home/pricing.png", class: "pricing", alt:"" %>
								</div>
							</div>
							
							<div class="item">
								<div class="col-sm-6">
									<h1><span>E</span>-SHOPPER</h1>
									<h2>Free Ecommerce Template</h2>
									<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. </p>
									<button type="button" class="btn btn-default get">Get it now</button>
								</div>
								<div class="col-sm-6">
									<%= image_tag "themes/home/girl3.jpg", class: "girl img-responsive", alt:"" %>
									<%= image_tag "themes/home/pricing.png", class: "pricing", alt:"" %>
								</div>
							</div>
							
						</div>
						
						<a href="#slider-carousel" class="left control-carousel hidden-xs" data-slide="prev">
							<i class="fa fa-angle-left"></i>
						</a>
						<a href="#slider-carousel" class="right control-carousel hidden-xs" data-slide="next">
							<i class="fa fa-angle-right"></i>
						</a>
					</div>
					
				</div>
			</div>
		</div>
	</section><!--/slider-->

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Admin site</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    "admin", media: "all" %>
    <%= javascript_include_tag "admin" %>
  </head>

  <body cz-shortcut-listen="true">
    <div class="row">
      <%= render "admins/shared/admin_header" %>
    </div>
    <div class="row">
      <%= yield %>
    </div>
    <footer><%= render "admins/shared/admin_footer"%></footer>
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>LoiNga</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>